version: "3.8"

services:
  #docker run -dit --name mydb1 --network lwnet -e MYSQL_ROOT_PASSWORD=REDHAT -e MYSQL_DATABASE=mydb -e MYSQL_USER=omkar -e MYSQL_PASSWORD=redhat -v /data:/var/lib/mysql mysql:latest
 
  db:
    image: mysql:latest
    container_name: mydb1
    network: 
    - lwnet
    volumes: 
    - /data:/var/lib/mysql
   
    environment:
      
    - MYSQL_ROOT_PASSWORD: redhat
    - MYSQL_DATABASE: mydb
    - MYSQL_USER: omkar 
    - MYSQL_PASSWORD: redhat    

#docker run -dit --name mywp1 --network lwnet -p 8080:80 wordpress:latest
  wp:
    depends_on:                          #depends on db service it will run after db run
    - db
    image: wordpress:latest
    container_name: mywp1
    networks:
    - lwnet
    ports: 
    - 8080:80  
    environment:
    - WORDPRESS_DB_HOST=mydb1
    - WORDPRESS_DB_USER=omkar
    - WORDPRESS_DB_PASSWORD=redhat
    - WORDPRESS_DB_NAME=mydb
    

networks:
  lwnet:
    driver: bridge 
